FROM php:fpm-stretch

RUN apt-get update && apt-get install -y

RUN apt-get update && apt-get install -y \
        git \
        zlib1g-dev \
        libxml2-dev \
        libzip-dev \
    && docker-php-ext-install \
        zip \
        intl \
		mysqli \
        pdo pdo_mysql
        
RUN pecl install xdebug
#RUN docker-php-ext-enable xdebug
RUN mkdir -p /home/xdebug
COPY ./docker/xdebug-debug.ini /home/xdebug/xdebug-debug.ini
COPY ./docker/xdebug-default.ini /home/xdebug/xdebug-default.ini
COPY ./docker/xdebug-off.ini /home/xdebug/xdebug-off.ini
COPY ./docker/xdebug-profile.ini /home/xdebug/xdebug-profile.ini
COPY ./docker/xdebug-trace.ini /home/xdebug/xdebug-trace.ini

ARG XDEBUG_MODES
ARG REMOTE_HOST="host.docker.internal"
ARG REMOTE_PORT=9003
ARG IDE_KEY="PHPSTORM"

ENV MODES=$XDEBUG_MODES
ENV CLIENT_HOST=$REMOTE_HOST
ENV CLIENT_PORT=$REMOTE_PORT
ENV IDEKEY=$IDE_KEY

COPY ./docker/fpm-entrypoint.sh /home/fpm-entrypoint
RUN chmod +x /home/fpm-entrypoint

COPY php.ini /usr/local/etc/php/
COPY . /var/www/html/
    
RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
COPY symfony/ /var/www/symfony
WORKDIR /var/www/symfony/

ENTRYPOINT ["/home/fpm-entrypoint"]